name: py312_blas
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - adwaita-icon-theme=49.0=unix_0
  - arviz=0.22.0=pyhcf101f3_1
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - binutils_impl_linux-64=2.45=default_hfdba357_104
  - binutils_linux-64=2.45=default_h4852527_104
  - blas=2.304=mkl
  - blas-devel=3.11.0=4_hcf00494_mkl
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.2=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - conda-gcc-specs=14.3.0=he8ccf15_15
  - cons=0.4.7=pyhd8ed1ab_2
  - contourpy=1.3.3=py312hd9148b4_3
  - cycler=0.12.1=pyhcf101f3_2
  - dbus=1.16.2=h24cb091_1
  - epoxy=1.5.10=hb03c661_2
  - etuples=0.3.10=pyhd8ed1ab_1
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py312h8a5da7c_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc=14.3.0=h0dff253_15
  - gcc_impl_linux-64=14.3.0=h319ec69_15
  - gcc_linux-64=14.3.0=h298d278_14
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - glib-tools=2.86.2=hf516916_1
  - graphite2=1.3.14=hecca717_2
  - graphviz=14.1.0=h8b86629_0
  - gtk3=3.24.43=h993cebd_6
  - gts=0.7.6=h977cf35_4
  - gxx=14.3.0=h76987e4_15
  - gxx_impl_linux-64=14.3.0=h2185e75_15
  - gxx_linux-64=14.3.0=hcfe7c2f_14
  - h5netcdf=1.7.3=pyhd8ed1ab_0
  - h5py=3.15.1=nompi_py312ha4f8f14_101
  - harfbuzz=12.2.0=h15599e2_0
  - hdf5=1.14.6=nompi_h1b119a7_104
  - hicolor-icon-theme=0.17=ha770c72_2
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.11.0=4_h5875eb1_mkl
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=4_hfef963f_mkl
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libegl-devel=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_15
  - libgcc-devel_linux-64=14.3.0=hf649bbc_115
  - libgcc-ng=15.2.0=h69a702a_15
  - libgd=2.3.3=h6f5c62b_11
  - libgfortran=15.2.0=h69a702a_15
  - libgfortran5=15.2.0=h68bc16d_15
  - libgl=1.7.0=ha4b6fd6_2
  - libgl-devel=1.7.0=ha4b6fd6_2
  - libglib=2.86.2=h6548e54_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libglx-devel=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_15
  - libhwloc=2.12.1=default_hafda6a7_1003
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=4_h5e43f62_mkl
  - liblapacke=3.11.0=4_hdba1596_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.53=h421ea60_0
  - librsvg=2.60.0=h61e6d4b_0
  - libsanitizer=14.3.0=h8f1669f_15
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_15
  - libstdcxx-devel_linux-64=14.3.0=h9f08a49_115
  - libstdcxx-ng=15.2.0=hdf11a46_15
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.2=h5347b49_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.7=h4922eb0_0
  - logical-unification=0.4.7=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - matplotlib-base=3.10.8=py312he3d6523_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minikanren=1.0.5=pyhd8ed1ab_1
  - mkl=2025.3.0=h0e700b2_462
  - mkl-devel=2025.3.0=ha770c72_462
  - mkl-include=2025.3.0=hf2ce2f3_462
  - mkl-service=2.6.0=py312h4307cf8_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.3.5=py312h33ff503_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - pango=1.56.4=hadf4263_0
  - pcre2=10.47=haa7fec5_0
  - pillow=12.0.0=py312h50c33e8_2
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymc=5.26.1=haba0287_1
  - pymc-base=5.26.1=pyhcf101f3_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pytensor=2.35.1=py312h68ae871_0
  - pytensor-base=2.35.1=np2py312h0f77346_0
  - python=3.12.12=hd63d673_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8c095d6_2
  - rich=14.2.0=pyhcf101f3_0
  - scipy=1.16.3=py312h7a1785b_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2022.3.0=h8d10470_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_ha0e22de_103
  - toolz=1.1.0=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py312h4c3975b_1
  - wayland=1.24.0=hd6090a7_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xarray=2025.12.0=pyhcf101f3_0
  - xarray-einstats=0.9.1=pyhd8ed1ab_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - zlib-ng=2.3.2=h54a6638_0
  - zstd=1.5.7=hb78ec9c_6
